name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel git
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Criar diretórios esperados do SDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/platform-tools
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/platforms/android-31

    - name: Build APK com Buildozer
      run: |
        buildozer android debug

    - name: Upload do APK
      uses: actions/upload-artifact@v3
      with:
        name: alarmvideoapp.apk
        path: bin/*.apk
