name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel wget
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Download and setup Android SDK command line tools
      run: |
        mkdir -p $HOME/.android/cmdline-tools
        cd $HOME/.android/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip
        rm tools.zip
        mv cmdline-tools latest

    - name: Install Android SDK components
      run: |
        export ANDROID_HOME=$HOME/.android
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK with Buildozer
      run: |
        export ANDROID_HOME=$HOME/.android
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: alarmvideoapp
        path: bin/*.apk

      uses: actions/upload-artifact@v4
      with:
        name: alarmvideoapp
        path: bin/*.apk
