name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel git wget

    - name: Install Android SDK (correct approach)
      run: |
        mkdir -p $ANDROID_SDK_ROOT
        cd $ANDROID_SDK_ROOT
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        mkdir cmdline-tools
        mv tools cmdline-tools/latest
        
        # Verify installation
        ls -la $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/

    - name: Set up Android SDK
      run: |
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        echo "Android SDK setup complete"

    - name: Build APK
      env:
        ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
        ANDROIDNDK: $HOME/.buildozer/android/platform/android-ndk-r25b
        ANDROIDAPI: 31
        ANDROIDMINAPI: 21
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.36
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: alarmvideoapp.apk
        path: bin/*.apk
