name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel git wget
        pip install --upgrade buildozer cython==0.29.36

    - name: Manually install Android SDK Build Tools
      run: |
        mkdir -p ~/.android/sdk/cmdline-tools
        cd ~/.android/sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        export ANDROID_HOME=$HOME/.android/sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        sdkmanager --sdk_root=$ANDROID_HOME "build-tools;31.0.0" "platforms;android-31" "platform-tools"

    - name: Build APK
      run: |
        export ANDROIDSDK=$HOME/.android/sdk
        export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: alarmvideoapp
        path: bin/*.apk

