name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel git wget

    - name: Install Android SDK command line tools
  run: |
    mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
    cd $ANDROID_SDK_ROOT/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
    unzip tools.zip
    mkdir latest
    mv cmdline-tools/* latest/
    rm -rf cmdline-tools tools.zip


    - name: Accept licenses and install build tools
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK
      env:
        ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
        ANDROIDNDK: $HOME/.buildozer/android/platform/android-ndk-r25b
        ANDROIDAPI: 31
        ANDROIDMINAPI: 21
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: alarmvideoapp.apk
        path: bin/*.apk
